services:
  airline-db:
    build: database/
    image: airline_db:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${PGPORT}:${PGPORT}"
    expose:
      - "${PGPORT}"
    environment:
      POSTGRES_PASSWORD: test123
      PGPORT: ${PGPORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 3

  airline-server:
    build: server/
    image: airline_server:latest
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - path: .env
        required: true
    depends_on:
      airline-db:
        condition: service_healthy
    command: ["npm", "start"]
